version: '3'
services:
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    ports:
      - "5500:80"  # Expose port 80 of the container as 8080 on the host
    networks:
      - mynetwork

  backend:
    build:
      context: ./backend  # Path to the backend directory
    ports:
      - "5000:5000"  # Expose port 5000 of the container as 5000 on the host
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge