services:
  backend:
    build: .
    container_name: websocket-backend
    ports:
      - "5000:5000"        # Expose port 5000 on the host
    environment:
      - FLASK_ENV=production   # Set Flask to production mode
    volumes:
      - ./backend:/app    # Bind mount your backend folder to the container
    networks:
      - websocket-network  # Connect to a custom network
    restart: always        # Always restart the container if it crashes
    logging:
      driver: "json-file"   # Configure logging format
      options:
        max-size: "10m"     # Limit log size to 10MB
        max-file: "3"       # Keep only 3 rotated log files

networks:
  websocket-network:
    driver: bridge